# Generated by Django 2.1.7 on 2019-04-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
    ]
