# Generated by Django 2.1.7 on 2019-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamestate_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.ForeignKey(null=True, on_delete=False, to='api.Room'),
        ),
    ]
