# Generated by Django 2.1.7 on 2019-04-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190423_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='whose_turn',
            field=models.ForeignKey(on_delete=False, to='api.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='location',
            field=models.OneToOneField(null=True, on_delete=False, to='api.Room'),
        ),
    ]
