# Generated by Django 2.1.7 on 2019-04-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190424_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
